// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgXwunfpolnbMK1QbH1mmABcMS9eoLNEE',
    appId: '1:843026121019:android:8d5a36cf976c15ab40371e',
    messagingSenderId: '843026121019',
    projectId: 'globe-care-doctor',

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa0wE4khP19gxMSPHKfchUeR7XQhqhIGc',
    appId: '1:979182963538:ios:6432dccffa95f1c2c3c88b',
    messagingSenderId: '979182963538',
    projectId: 'globe-care-6b8d8',

    iosClientId:
        '979182963538-g5lce0m8kd5piuabi2d0b2o54i2n1ald.apps.googleusercontent.com',
    iosBundleId: 'com.app.globcare',
  );

}
